<?php

/*
 *
 * (c) 2015 Okta Purnama Rahadian <okta.rahadian@hotmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Wikusama\Bundle\Wikufest\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileRepository extends EntityRepository
{
    public function loadUserProfileByUsername($username)
    {
       $dbConnection = $this->getEntityManager()->getConnection();
       
       $sql = "SELECT 
                `u`.`id` AS users_id, 
                `u`.`username` AS users_username, 
                `u`.`password` AS users_password, 
                `u`.`email` AS users_email, 
                `u`.`is_active` AS users_is_active,
                `up`.`id`, `up`.`user_id`, `up`.`fullname`, `up`.`is_have_promocode`, `up`.`occupacy`, `up`.`company_name`, `up`.`summary`, `up`.`account_activation`, `up`.`profile_picture_path`, `up`.`twitter_account`, `up`.`facebook_account`, `up`.`linkedin_account`, `up`.`student_class_name`, `up`.`student_id_number`, `up`.`phone_number`, `up`.`date_created`, `up`.`gender`
                 FROM `users` `u` LEFT JOIN
                 `user_profiles` `up` ON (u.id=up.user_id)
                 WHERE LOWER(`u`.`username`) = LOWER(?)";
   
        return $dbConnection->fetchAssoc($sql, [$username]);
    }
}
