wikufest_dashboard:
    resource: "@WikusamaWikufestAppBundle/Resources/config/routing.yml"
    prefix:   /

app_login:
    path:     /Login
    defaults: { _controller: WikusamaWikufestAppBundle:UserAccount/Login:index }
    
app_default:
    path: /Default
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'WikusamaWikufestAppBundle::landing.html.twig'

app_login_check:
    path:     /LoginCheck
    
app_logout:
    path:     /Logout

    
# app:
#    resource: @AppBundle/Controller/
#    type:     annotation
