security:
    encoders:
        Wikusama\Bundle\Wikufest\AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 13
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        
            
    providers:
        main:
            entity: { class: Wikusama\Bundle\Wikufest\AppBundle\Entity\User }
#        in_memory:
#            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
#        login:
#            pattern:  ^/login
#            security: false
        
#        default:
#            anonymous: ~
            
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: app_login
                check_path: app_login_check
                csrf_provider: form.csrf_provider
                use_referer: true
            logout:
                path:   /Logout
                target: /
                invalidate_session: true
            
    access_control:
        - { path: ^/Login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/Default, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }