wikufest_homepage:
    path: /
    defaults: { _controller: WikusamaWikufestAppBundle:Home\Home:index }
    
wikufest_useraccount_createuseraccount_loadfromfile:
    path: /UserAccount/CreateUserAccount/LoadFromFile
    defaults: { _controller: WikusamaWikufestAppBundle:UserAccount/CreateUserAccount:loadFromFile }
    
wikufest_useraccount_activateuseraccount_default:
    path: /UserAccount/ActivateUserAccount/Default
    defaults: { _controller: WikusamaWikufestAppBundle:UserAccount/ActivateUserAccount:default }
    
wikufest_useraccount_activateuseraccount_loadfromfile:
    path: /UserAccount/ActivateUserAccount/LoadFromFile
    defaults: { _controller: WikusamaWikufestAppBundle:UserAccount/ActivateUserAccount:loadFromFile }

wikufest_useraccount_activateuseraccount_activatesingleaccount:
    path: /UserAccount/ActivateUserAccount/ActivateSingleAccount
    defaults: { _controller: WikusamaWikufestAppBundle:UserAccount/ActivateUserAccount:activateSingleAccount }
    
wikufest_course_registeraudiencetocoursesession:
    path: /Course/RegisterAudienceToCourseSession
    defaults: { _controller: WikusamaWikufestAppBundle:Course/RegisterAudienceToCourseSession:index }
    
wikufest_course_registeraudiencetocoursesession_process:
    path: /Course/RegisterAudienceToCourseSession/Process
    defaults: { _controller: WikusamaWikufestAppBundle:Course/RegisterAudienceToCourseSession:process }

